import type { Express } from "express";

import route1 from "./routes/agent";
import route2 from "./routes/agent/answer";
import route3 from "./routes/agent/canvasResult";
import route4 from "./routes/agent/create";
import route5 from "./routes/agent/get";
import route6 from "./routes/agent/list";
import route7 from "./routes/agent/mentionSource";
import route8 from "./routes/agent/message";
import route9 from "./routes/agent/rename";
import route10 from "./routes/agent/skills";
import route11 from "./routes/agent/stop";
import route12 from "./routes/agents/a2a/get";
import route13 from "./routes/agents/a2a/save";
import route14 from "./routes/agents/connect";
import route15 from "./routes/agents/get";
import route16 from "./routes/agents/install";
import route17 from "./routes/agents/read";
import route18 from "./routes/agents/save";
import route19 from "./routes/agents/setEnabled";
import route20 from "./routes/agents/uninstall";
import route21 from "./routes/ai/generate";
import route22 from "./routes/ai/media/cancel";
import route23 from "./routes/ai/media/generate";
import route24 from "./routes/ai/media/models";
import route25 from "./routes/ai/media/production";
import route26 from "./routes/ai/models";
import route27 from "./routes/ai/trial";
import route28 from "./routes/assets/list";
import route29 from "./routes/assets/mkdir";
import route30 from "./routes/assets/read";
import route31 from "./routes/assets/remove";
import route32 from "./routes/assets/rename";
import route33 from "./routes/assets/save";
import route34 from "./routes/desktop/clipboard/read";
import route35 from "./routes/desktop/clipboard/write";
import route36 from "./routes/desktop/devtools";
import route37 from "./routes/desktop/openUrl";
import route38 from "./routes/desktop/plugins/install";
import route39 from "./routes/desktop/providerFile/read";
import route40 from "./routes/desktop/providerFile/select";
import route41 from "./routes/desktop/ready";
import route42 from "./routes/desktop/saveFile";
import route43 from "./routes/desktop/selectDirectory";
import route44 from "./routes/desktop/selectSaveFile";
import route45 from "./routes/desktop/update/apply";
import route46 from "./routes/desktop/update/check";
import route47 from "./routes/desktop/update/download";
import route48 from "./routes/desktop/update/index";
import route49 from "./routes/ffmpeg/cancel";
import route50 from "./routes/ffmpeg/download";
import route51 from "./routes/ffmpeg/events";
import route52 from "./routes/ffmpeg/execute";
import route53 from "./routes/ffmpeg/progress";
import route54 from "./routes/ffmpeg/status";
import route55 from "./routes/mcp/control/events";
import route56 from "./routes/mcp/control/result";
import route57 from "./routes/mcp/control/state";
import route58 from "./routes/mcp/skill";
import route59 from "./routes/mcp/status";
import route60 from "./routes/nodes/files";
import route61 from "./routes/nodes/get";
import route62 from "./routes/nodes/install";
import route63 from "./routes/nodes/save";
import route64 from "./routes/nodes/setEnabled";
import route65 from "./routes/nodes/uninstall";
import route66 from "./routes/plugins/export";
import route67 from "./routes/providers/debug/inspect";
import route68 from "./routes/providers/debug/run";
import route69 from "./routes/providers/media/add";
import route70 from "./routes/providers/media/delete";
import route71 from "./routes/providers/media/list";
import route72 from "./routes/providers/media/models";
import route73 from "./routes/providers/media/save";
import route74 from "./routes/providers/models";
import route75 from "./routes/providers/test";
import route76 from "./routes/settings/get";
import route77 from "./routes/settings/personalization/get";
import route78 from "./routes/settings/personalization/save";
import route79 from "./routes/settings/save";
import route80 from "./routes/settings/systemPrompt";
import route81 from "./routes/skills/create";
import route82 from "./routes/skills/get";
import route83 from "./routes/skills/install";
import route84 from "./routes/skills/list";
import route85 from "./routes/skills/move";
import route86 from "./routes/skills/order";
import route87 from "./routes/skills/read";
import route88 from "./routes/skills/save";
import route89 from "./routes/skills/uninstall";
import route90 from "./routes/tools/client";
import route91 from "./routes/tools/get";
import route92 from "./routes/tools/install";
import route93 from "./routes/tools/renderers";
import route94 from "./routes/tools/save";
import route95 from "./routes/tools/setEnabled";
import route96 from "./routes/tools/uninstall";
import route97 from "./routes/workspaces/check";
import route98 from "./routes/workspaces/createProject";
import route99 from "./routes/workspaces/files/list";
import route100 from "./routes/workspaces/files/mkdir";
import route101 from "./routes/workspaces/files/read";
import route102 from "./routes/workspaces/files/remove";
import route103 from "./routes/workspaces/files/rename";
import route104 from "./routes/workspaces/files/write";
import route105 from "./routes/workspaces/list";
import route106 from "./routes/workspaces/selectDirectory";

export default (app: Express) => {
  app.use("/api/agent", route1);
  app.use("/api/agent/answer", route2);
  app.use("/api/agent/canvasResult", route3);
  app.use("/api/agent/create", route4);
  app.use("/api/agent/get", route5);
  app.use("/api/agent/list", route6);
  app.use("/api/agent/mentionSource", route7);
  app.use("/api/agent/message", route8);
  app.use("/api/agent/rename", route9);
  app.use("/api/agent/skills", route10);
  app.use("/api/agent/stop", route11);
  app.use("/api/agents/a2a/get", route12);
  app.use("/api/agents/a2a/save", route13);
  app.use("/api/agents/connect", route14);
  app.use("/api/agents/get", route15);
  app.use("/api/agents/install", route16);
  app.use("/api/agents/read", route17);
  app.use("/api/agents/save", route18);
  app.use("/api/agents/setEnabled", route19);
  app.use("/api/agents/uninstall", route20);
  app.use("/api/ai/generate", route21);
  app.use("/api/ai/media/cancel", route22);
  app.use("/api/ai/media/generate", route23);
  app.use("/api/ai/media/models", route24);
  app.use("/api/ai/media/production", route25);
  app.use("/api/ai/models", route26);
  app.use("/api/ai/trial", route27);
  app.use("/api/assets/list", route28);
  app.use("/api/assets/mkdir", route29);
  app.use("/api/assets/read", route30);
  app.use("/api/assets/remove", route31);
  app.use("/api/assets/rename", route32);
  app.use("/api/assets/save", route33);
  app.use("/api/desktop/clipboard/read", route34);
  app.use("/api/desktop/clipboard/write", route35);
  app.use("/api/desktop/devtools", route36);
  app.use("/api/desktop/openUrl", route37);
  app.use("/api/desktop/plugins/install", route38);
  app.use("/api/desktop/providerFile/read", route39);
  app.use("/api/desktop/providerFile/select", route40);
  app.use("/api/desktop/ready", route41);
  app.use("/api/desktop/saveFile", route42);
  app.use("/api/desktop/selectDirectory", route43);
  app.use("/api/desktop/selectSaveFile", route44);
  app.use("/api/desktop/update/apply", route45);
  app.use("/api/desktop/update/check", route46);
  app.use("/api/desktop/update/download", route47);
  app.use("/api/desktop/update", route48);
  app.use("/api/ffmpeg/cancel", route49);
  app.use("/api/ffmpeg/download", route50);
  app.use("/api/ffmpeg/events", route51);
  app.use("/api/ffmpeg/execute", route52);
  app.use("/api/ffmpeg/progress", route53);
  app.use("/api/ffmpeg/status", route54);
  app.use("/api/mcp/control/events", route55);
  app.use("/api/mcp/control/result", route56);
  app.use("/api/mcp/control/state", route57);
  app.use("/api/mcp/skill", route58);
  app.use("/api/mcp/status", route59);
  app.use("/api/nodes/files", route60);
  app.use("/api/nodes/get", route61);
  app.use("/api/nodes/install", route62);
  app.use("/api/nodes/save", route63);
  app.use("/api/nodes/setEnabled", route64);
  app.use("/api/nodes/uninstall", route65);
  app.use("/api/plugins/export", route66);
  app.use("/api/providers/debug/inspect", route67);
  app.use("/api/providers/debug/run", route68);
  app.use("/api/providers/media/add", route69);
  app.use("/api/providers/media/delete", route70);
  app.use("/api/providers/media/list", route71);
  app.use("/api/providers/media/models", route72);
  app.use("/api/providers/media/save", route73);
  app.use("/api/providers/models", route74);
  app.use("/api/providers/test", route75);
  app.use("/api/settings/get", route76);
  app.use("/api/settings/personalization/get", route77);
  app.use("/api/settings/personalization/save", route78);
  app.use("/api/settings/save", route79);
  app.use("/api/settings/systemPrompt", route80);
  app.use("/api/skills/create", route81);
  app.use("/api/skills/get", route82);
  app.use("/api/skills/install", route83);
  app.use("/api/skills/list", route84);
  app.use("/api/skills/move", route85);
  app.use("/api/skills/order", route86);
  app.use("/api/skills/read", route87);
  app.use("/api/skills/save", route88);
  app.use("/api/skills/uninstall", route89);
  app.use("/api/tools/client", route90);
  app.use("/api/tools/get", route91);
  app.use("/api/tools/install", route92);
  app.use("/api/tools/renderers", route93);
  app.use("/api/tools/save", route94);
  app.use("/api/tools/setEnabled", route95);
  app.use("/api/tools/uninstall", route96);
  app.use("/api/workspaces/check", route97);
  app.use("/api/workspaces/createProject", route98);
  app.use("/api/workspaces/files/list", route99);
  app.use("/api/workspaces/files/mkdir", route100);
  app.use("/api/workspaces/files/read", route101);
  app.use("/api/workspaces/files/remove", route102);
  app.use("/api/workspaces/files/rename", route103);
  app.use("/api/workspaces/files/write", route104);
  app.use("/api/workspaces/list", route105);
  app.use("/api/workspaces/selectDirectory", route106);
}
